availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/CREDENTIALS_ADMIN/versions/latest
      env: CREDENTIALS_ADMIN
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_URL/versions/latest
      env: FIREBASE_URL
steps:
  # Docker イメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'apps/user-profile-service/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/user-profile-service:$BUILD_ID', './apps/user-profile-service']
  # Container Registry にプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/user-profile-service:$BUILD_ID']
  # Cloud Run にデプロイ
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    secretEnv:
      - CREDENTIALS_ADMIN
      - FIREBASE_URL
    args:
      - -c
      - |
        gcloud run deploy user-profile-service \
          --image gcr.io/$PROJECT_ID/user-profile-service:$BUILD_ID \
          --region asia-northeast1 \
          --platform managed \
          --allow-unauthenticated \
            --set-secrets=CREDENTIALS_ADMIN=CREDENTIALS_ADMIN:latest,FIREBASE_URL=FIREBASE_URL:latest
