availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/RAKUTEN_APPLICATION_ID/versions/latest
      env: RAKUTEN_APPLICATION_ID
    - versionName: projects/$PROJECT_ID/secrets/RAKUTEN_AFFILIATE_ID/versions/latest
      env: RAKUTEN_AFFILIATE_ID
steps:
  # Docker イメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'apps/rakuten-server/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/rakuten-server:$BUILD_ID', './apps/rakuten-server']
  # Container Registry にプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/rakuten-server:$BUILD_ID']
  # Cloud Run にデプロイ
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    secretEnv:
      - RAKUTEN_APPLICATION_ID
      - RAKUTEN_AFFILIATE_ID
    args:
      - -c
      - |
        gcloud run deploy rakuten-server \
          --image gcr.io/$PROJECT_ID/rakuten-server:$BUILD_ID \
          --region asia-northeast1 \
          --platform managed \
          --allow-unauthenticated \
            --set-secrets=RAKUTEN_APPLICATION_ID=RAKUTEN_APPLICATION_ID:latest,RAKUTEN_AFFILIATE_ID=RAKUTEN_AFFILIATE_ID:latest
