name: Continuous Integration

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ develop, feature/* ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.19.3]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint (if configured)
      run: npm run lint --if-present

    - name: Run TypeScript compiler check
      run: npx tsc --noEmit

    - name: Build TypeScript
      run: npm run build

    - name: Run unit tests
      run: npm test
      env:
        NODE_ENV: test
        # テスト用のモック環境変数
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        CHANNEL_ACCESS: test-channel-access
        CHANNEL_SECRET: test-channel-secret
        CREDENTIALS_ADMIN: dGVzdA==
        CREDENTIALS: dGVzdA==
        FIREBASE_URL: https://test.firebaseio.com
        SPREADSHEET_ID: test-spreadsheet-id
        CO_API_KEY: test-co-api-key
        RAKUTEN_APPLICATION_ID: test-rakuten-app-id
        RAKUTEN_AFFILIATE_ID: test-rakuten-affiliate-id

    - name: Test Docker build
      run: |-
        docker build -f infrastructure/docker/Dockerfile.kame-buttler -t turtle-buttler:test .
        echo "✅ Docker build successful"

  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run npm audit
      run: npm audit --audit-level moderate

    - name: Check for secrets in code
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: main
        head: HEAD